### ISSUE TITLE
Missing go crypto package

### ISSUE THREAD

**Issue by kaminek** [evilsocket/arc#94]
Hi @evilsocket,

when building from source I get,

```
pgp/encrypt.go:15:2: cannot find package "golang.org/x/crypto/openpgp" in any of:
        /usr/local/go/src/golang.org/x/crypto/openpgp (from $GOROOT)
        /home/kherbouche/Work/go/src/github.com/evilsocket/arc/arcd/_vendor/src/golang.org/x/crypto/openpgp (from $GOPATH)
        /home/kherbouche/Work/go/src/golang.org/x/crypto/openpgp
pgp/encrypt.go:16:2: cannot find package "golang.org/x/crypto/openpgp/armor" in any of:
        /usr/local/go/src/golang.org/x/crypto/openpgp/armor (from $GOROOT)
        /home/kherbouche/Work/go/src/github.com/evilsocket/arc/arcd/_vendor/src/golang.org/x/crypto/openpgp/armor (from $GOPATH)
        /home/kherbouche/Work/go/src/golang.org/x/crypto/openpgp/armor
pgp/encrypt.go:17:2: cannot find package "golang.org/x/crypto/openpgp/packet" in any of:
        /usr/local/go/src/golang.org/x/crypto/openpgp/packet (from $GOROOT)
        /home/kherbouche/Work/go/src/github.com/evilsocket/arc/arcd/_vendor/src/golang.org/x/crypto/openpgp/packet (from $GOPATH)
        /home/kherbouche/Work/go/src/golang.org/x/crypto/openpgp/packet
pgp/encrypt.go:18:2: cannot find package "golang.org/x/crypto/ripemd160" in any of:
        /usr/local/go/src/golang.org/x/crypto/ripemd160 (from $GOROOT)
        /home/kherbouche/Work/go/src/github.com/evilsocket/arc/arcd/_vendor/src/golang.org/x/crypto/ripemd160 (from $GOPATH)
        /home/kherbouche/Work/go/src/golang.org/x/crypto/ripemd160
Makefile:21: recipe for target 'build' failed
make: *** [build] Error 1
```

This is due to missing package in dependancies.

I have a fix (just adding golang.org/x/crypto/... to dependancies) and I'm reworking the Makefile accordingly

**Comment by jemacom** [comment]
Dupicate #92. I think this is has been solved here #91. :smile:

**Comment by kaminek** [comment]
I had the patch of #91 and it didn't fix it because it's a missing package not a path.

**Comment by Bedotech** [comment]
Fixed in #93
